services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: onlinejudge-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: onlinejudge
    volumes:
      - mongodb_data:/data/db
    networks:
      - onlinejudge-network

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onlinejudge-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/onlinejudge?authSource=admin
      JWT_SECRET: your-secret-key-here
      PORT: 5000
    depends_on:
      - mongodb
    volumes:
      - ./Backend:/app
      - /app/node_modules
    networks:
      - onlinejudge-network

  # Compiler Service
  compiler:
    build:
      context: ./Compiler
      dockerfile: Dockerfile
    container_name: onlinejudge-compiler
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
    volumes:
      - ./Compiler:/app
      - /app/node_modules
    networks:
      - onlinejudge-network

  # Frontend Service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: onlinejudge-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - onlinejudge-network

volumes:
  mongodb_data:

networks:
  onlinejudge-network:
    driver: bridge
