services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: onlinejudge-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: onlinejudge
    volumes:
      - mongodb_data:/data/db
    networks:
      - onlinejudge-network

  # Backend API Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: onlinejudge-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./Compiler:/app/Compiler:rw
      - ./Backend:/app/Backend:ro
    working_dir: /app/Backend
    networks:
      - onlinejudge-network
    # Security enhancements
    read_only: true
    tmpfs:
      - /tmp
      - /app/Backend/logs
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  # Compiler Service
  compiler:
    build:
      context: ./Compiler
      dockerfile: Dockerfile
    container_name: onlinejudge-compiler
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
    volumes:
      - ./Compiler:/app/Compiler:ro
      - compiler_sandbox:/tmp/sandbox
    working_dir: /app/Compiler
    networks:
      - onlinejudge-network
    # Security enhancements for compiler
    read_only: true
    tmpfs:
      - /tmp
      - /app/Compiler/codes
      - /app/Compiler/outputs
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    mem_limit: 512m
    cpus: 1.0
    pids_limit: 50

  # Frontend Service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: onlinejudge-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - onlinejudge-network

volumes:
  mongodb_data:
  compiler_sandbox:

networks:
  onlinejudge-network:
    driver: bridge
